
import { EventType } from '@/types';

export const EVENT_TYPES: Record<EventType, string> = {
  pass: 'Pass',
  shot: 'Shot',
  tackle: 'Tackle',
  foul: 'Foul',
  corner: 'Corner',
  offside: 'Offside',
  goal: 'Goal',
  assist: 'Assist',
  yellowCard: 'Yellow Card',
  redCard: 'Red Card',
  substitution: 'Substitution',
  card: 'Card',
  penalty: 'Penalty',
  'free-kick': 'Free Kick',
  'goal-kick': 'Goal Kick',
  'throw-in': 'Throw In',
  interception: 'Interception',
  possession: 'Possession',
  ballLost: 'Ball Lost',
  ballRecovered: 'Ball Recovered',
  dribble: 'Dribble',
  cross: 'Cross',
  clearance: 'Clearance',
  block: 'Block',
  save: 'Save',
  ownGoal: 'Own Goal',
  freeKick: 'Free Kick',
  throwIn: 'Throw In',
  goalKick: 'Goal Kick',
  aerialDuel: 'Aerial Duel',
  groundDuel: 'Ground Duel'
};

export const KEYBOARD_MAPPINGS: Record<EventType, string> = {
  pass: 'P',
  shot: 'S',
  tackle: 'T',
  foul: 'F',
  corner: 'C',
  offside: 'O',
  goal: 'G',
  assist: 'A',
  yellowCard: 'Y',
  redCard: 'R',
  substitution: 'U',
  card: 'K',
  penalty: 'E',
  'free-kick': 'Q',
  'goal-kick': 'L',
  'throw-in': 'H',
  interception: 'I',
  possession: 'B',
  ballLost: 'X',
  ballRecovered: 'V',
  dribble: 'D',
  cross: 'Z',
  clearance: 'W',
  block: 'M',
  save: 'N',
  ownGoal: 'J',
  freeKick: '1',
  throwIn: '2',
  goalKick: '3',
  aerialDuel: '4',
  groundDuel: '5'
};
