
import { EventType } from '@/types';

export const eventTypeLabels: Record<EventType, string> = {
  pass: 'Pass',
  shot: 'Shot',
  tackle: 'Tackle',
  foul: 'Foul',
  corner: 'Corner',
  offside: 'Offside',
  goal: 'Goal',
  assist: 'Assist',
  yellowCard: 'Yellow Card',
  redCard: 'Red Card',
  substitution: 'Substitution',
  card: 'Card',
  penalty: 'Penalty',
  'free-kick': 'Free Kick',
  'goal-kick': 'Goal Kick',
  'throw-in': 'Throw In',
  interception: 'Interception',
  possession: 'Possession',
  ballLost: 'Ball Lost',
  ballRecovered: 'Ball Recovered',
  dribble: 'Dribble',
  cross: 'Cross',
  clearance: 'Clearance',
  block: 'Block',
  save: 'Save',
  ownGoal: 'Own Goal',
  freeKick: 'Free Kick',
  throwIn: 'Throw In',
  goalKick: 'Goal Kick',
  aerialDuel: 'Aerial Duel',
  groundDuel: 'Ground Duel'
};

export const eventTypeDescriptions: Record<EventType, string> = {
  pass: 'A successful pass between players',
  shot: 'An attempt at goal',
  tackle: 'A defensive action to win the ball',
  foul: 'A rule violation',
  corner: 'A corner kick',
  offside: 'An offside offense',
  goal: 'A goal scored',
  assist: 'An assist for a goal',
  yellowCard: 'A yellow card shown',
  redCard: 'A red card shown',
  substitution: 'A player substitution',
  card: 'A card shown to a player',
  penalty: 'A penalty kick',
  'free-kick': 'A free kick awarded',
  'goal-kick': 'A goal kick',
  'throw-in': 'A throw in',
  interception: 'Ball intercepted',
  possession: 'Ball possession',
  ballLost: 'Ball lost',
  ballRecovered: 'Ball recovered',
  dribble: 'Dribbling action',
  cross: 'Cross into the box',
  clearance: 'Defensive clearance',
  block: 'Shot blocked',
  save: 'Goalkeeper save',
  ownGoal: 'Own goal scored',
  freeKick: 'Free kick',
  throwIn: 'Throw in',
  goalKick: 'Goal kick',
  aerialDuel: 'Aerial duel',
  groundDuel: 'Ground duel'
};
