// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://adqdurdohxypzhfwxgll.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFkcWR1cmRvaHh5cHpoZnd4Z2xsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyMDcwMjQsImV4cCI6MjA2Mjc4MzAyNH0.LmZnI5xz7DHnnkolPrnQaZKJ7L-tlomWNE8Gbb1YaNg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);